from django.urls import path
from main.views import (
    show_main,
    show_experience,
    create_experience,
    update_experience,
    delete_experience,
    show_json_experiences,
    show_project,
    create_project,
    update_project,
    delete_project,
    show_json_projects,
    show_art,
    send_message,
    get_messages_json,
    delete_message,
    show_json_projects,
    register,
    login_user,
    logout_user,)
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('experience/', show_experience, name='show_experience'),
    path('projects/', show_project, name='show_project'),
    path('projects/add/', create_project, name='create_project'),
    path('projects/edit/<int:id>/', update_project, name='update_project'),
    path('projects/delete/<int:id>/', delete_project, name='delete_project'),
    path('projects/json/', show_json_projects, name='show_json_projects'),
    path('art/', show_art, name='show_art'),
    path('pesan/', send_message, name='send_message'),
    path("api/messages/", get_messages_json, name="get_messages_json"),
    path("pesan/<int:message_id>/delete/", delete_message, name="delete_message"),
    path('experience/', show_experience, name='show_experience'),
    path('experience/add/', create_experience, name='create_experience'),
    path('experience/edit/<int:id>/', update_experience, name='update_experience'),
    path('experience/delete/<int:id>/', delete_experience, name='delete_experience'),
    path('experience/json/', show_json_experiences, name='show_json_experiences'),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
]