# Generated by Django 5.2.17 on 2026-09-27 13:16

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('characters', 'Characters'), ('backgrounds', 'Backgrounds'), ('icons', 'Vector Icons'), ('tilemaps', 'Tilemaps'), ('spritesheets', 'Spritesheets')], max_length=50)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('start_period', models.CharField(max_length=50)),
                ('end_period', models.CharField(default='Present', max_length=50)),
                ('logo_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('ACADEMIC', 'Academic'), ('INTERNSHIP', 'Internship')], default='ORGANIZATION', max_length=50)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('play_url', models.URLField()),
                ('starred_by', models.ManyToManyField(blank=True, related_name='starred_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
