# Generated by Django 5.2.17 on 2026-09-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('characters', 'Characters'), ('backgrounds', 'Backgrounds'), ('icons', 'Vector Icons'), ('tilemaps', 'Tilemaps'), ('spritesheets', 'Spritesheets')], max_length=50)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('start_period', models.CharField(max_length=50)),
                ('end_period', models.CharField(default='Present', max_length=50)),
                ('logo_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('ACADEMIC', 'Academic'), ('INTERNSHIP', 'Internship')], default='ORGANIZATION', max_length=50)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('play_url', models.URLField()),
            ],
        ),
    ]
