# Generated by Django 5.2.17 on 2026-09-28 04:23

from django.db import migrations

def create_editor_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Editor')
    
class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_starred_by'),
    ]

    operations = [
    ]
